/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'
import { Route as ProfilePaymentsRouteImport } from './routes/profile.payments'
import { Route as ProfileOrderHistoryRouteImport } from './routes/profile.order-history'
import { Route as ProfileNotificationsRouteImport } from './routes/profile.notifications'
import { Route as ProfileAddressesRouteImport } from './routes/profile.addresses'
import { Route as FoodIdRouteImport } from './routes/food.$id'
import { Route as ProfilePrivacyIndexRouteImport } from './routes/profile.privacy.index'
import { Route as ProfileHelpIndexRouteImport } from './routes/profile.help.index'
import { Route as ProfilePrivacy2faRouteImport } from './routes/profile.privacy.2fa'
import { Route as ProfilePlaceholderSlugRouteImport } from './routes/profile.placeholder.$slug'
import { Route as ProfileHelpChatRouteImport } from './routes/profile.help.chat'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePaymentsRoute = ProfilePaymentsRouteImport.update({
  id: '/profile/payments',
  path: '/profile/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOrderHistoryRoute = ProfileOrderHistoryRouteImport.update({
  id: '/profile/order-history',
  path: '/profile/order-history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsRoute = ProfileNotificationsRouteImport.update({
  id: '/profile/notifications',
  path: '/profile/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAddressesRoute = ProfileAddressesRouteImport.update({
  id: '/profile/addresses',
  path: '/profile/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodIdRoute = FoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyIndexRoute = ProfilePrivacyIndexRouteImport.update({
  id: '/profile/privacy/',
  path: '/profile/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpIndexRoute = ProfileHelpIndexRouteImport.update({
  id: '/profile/help/',
  path: '/profile/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacy2faRoute = ProfilePrivacy2faRouteImport.update({
  id: '/profile/privacy/2fa',
  path: '/profile/privacy/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePlaceholderSlugRoute = ProfilePlaceholderSlugRouteImport.update({
  id: '/profile/placeholder/$slug',
  path: '/profile/placeholder/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpChatRoute = ProfileHelpChatRouteImport.update({
  id: '/profile/help/chat',
  path: '/profile/help/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/track': typeof TrackRoute
  '/food/$id': typeof FoodIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/order-history': typeof ProfileOrderHistoryRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/help/chat': typeof ProfileHelpChatRoute
  '/profile/placeholder/$slug': typeof ProfilePlaceholderSlugRoute
  '/profile/privacy/2fa': typeof ProfilePrivacy2faRoute
  '/profile/help/': typeof ProfileHelpIndexRoute
  '/profile/privacy/': typeof ProfilePrivacyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/track': typeof TrackRoute
  '/food/$id': typeof FoodIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/order-history': typeof ProfileOrderHistoryRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/profile': typeof ProfileIndexRoute
  '/profile/help/chat': typeof ProfileHelpChatRoute
  '/profile/placeholder/$slug': typeof ProfilePlaceholderSlugRoute
  '/profile/privacy/2fa': typeof ProfilePrivacy2faRoute
  '/profile/help': typeof ProfileHelpIndexRoute
  '/profile/privacy': typeof ProfilePrivacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/search': typeof SearchRoute
  '/track': typeof TrackRoute
  '/food/$id': typeof FoodIdRoute
  '/profile/addresses': typeof ProfileAddressesRoute
  '/profile/notifications': typeof ProfileNotificationsRoute
  '/profile/order-history': typeof ProfileOrderHistoryRoute
  '/profile/payments': typeof ProfilePaymentsRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/profile/': typeof ProfileIndexRoute
  '/profile/help/chat': typeof ProfileHelpChatRoute
  '/profile/placeholder/$slug': typeof ProfilePlaceholderSlugRoute
  '/profile/privacy/2fa': typeof ProfilePrivacy2faRoute
  '/profile/help/': typeof ProfileHelpIndexRoute
  '/profile/privacy/': typeof ProfilePrivacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/payment'
    | '/search'
    | '/track'
    | '/food/$id'
    | '/profile/addresses'
    | '/profile/notifications'
    | '/profile/order-history'
    | '/profile/payments'
    | '/restaurant/$id'
    | '/profile/'
    | '/profile/help/chat'
    | '/profile/placeholder/$slug'
    | '/profile/privacy/2fa'
    | '/profile/help/'
    | '/profile/privacy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/payment'
    | '/search'
    | '/track'
    | '/food/$id'
    | '/profile/addresses'
    | '/profile/notifications'
    | '/profile/order-history'
    | '/profile/payments'
    | '/restaurant/$id'
    | '/profile'
    | '/profile/help/chat'
    | '/profile/placeholder/$slug'
    | '/profile/privacy/2fa'
    | '/profile/help'
    | '/profile/privacy'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/onboarding'
    | '/orders'
    | '/payment'
    | '/search'
    | '/track'
    | '/food/$id'
    | '/profile/addresses'
    | '/profile/notifications'
    | '/profile/order-history'
    | '/profile/payments'
    | '/restaurant/$id'
    | '/profile/'
    | '/profile/help/chat'
    | '/profile/placeholder/$slug'
    | '/profile/privacy/2fa'
    | '/profile/help/'
    | '/profile/privacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  SearchRoute: typeof SearchRoute
  TrackRoute: typeof TrackRoute
  FoodIdRoute: typeof FoodIdRoute
  ProfileAddressesRoute: typeof ProfileAddressesRoute
  ProfileNotificationsRoute: typeof ProfileNotificationsRoute
  ProfileOrderHistoryRoute: typeof ProfileOrderHistoryRoute
  ProfilePaymentsRoute: typeof ProfilePaymentsRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProfileHelpChatRoute: typeof ProfileHelpChatRoute
  ProfilePlaceholderSlugRoute: typeof ProfilePlaceholderSlugRoute
  ProfilePrivacy2faRoute: typeof ProfilePrivacy2faRoute
  ProfileHelpIndexRoute: typeof ProfileHelpIndexRoute
  ProfilePrivacyIndexRoute: typeof ProfilePrivacyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/payments': {
      id: '/profile/payments'
      path: '/profile/payments'
      fullPath: '/profile/payments'
      preLoaderRoute: typeof ProfilePaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/order-history': {
      id: '/profile/order-history'
      path: '/profile/order-history'
      fullPath: '/profile/order-history'
      preLoaderRoute: typeof ProfileOrderHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/notifications': {
      id: '/profile/notifications'
      path: '/profile/notifications'
      fullPath: '/profile/notifications'
      preLoaderRoute: typeof ProfileNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/addresses': {
      id: '/profile/addresses'
      path: '/profile/addresses'
      fullPath: '/profile/addresses'
      preLoaderRoute: typeof ProfileAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/$id': {
      id: '/food/$id'
      path: '/food/$id'
      fullPath: '/food/$id'
      preLoaderRoute: typeof FoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy/': {
      id: '/profile/privacy/'
      path: '/profile/privacy'
      fullPath: '/profile/privacy/'
      preLoaderRoute: typeof ProfilePrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/help/': {
      id: '/profile/help/'
      path: '/profile/help'
      fullPath: '/profile/help/'
      preLoaderRoute: typeof ProfileHelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy/2fa': {
      id: '/profile/privacy/2fa'
      path: '/profile/privacy/2fa'
      fullPath: '/profile/privacy/2fa'
      preLoaderRoute: typeof ProfilePrivacy2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/placeholder/$slug': {
      id: '/profile/placeholder/$slug'
      path: '/profile/placeholder/$slug'
      fullPath: '/profile/placeholder/$slug'
      preLoaderRoute: typeof ProfilePlaceholderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/help/chat': {
      id: '/profile/help/chat'
      path: '/profile/help/chat'
      fullPath: '/profile/help/chat'
      preLoaderRoute: typeof ProfileHelpChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  SearchRoute: SearchRoute,
  TrackRoute: TrackRoute,
  FoodIdRoute: FoodIdRoute,
  ProfileAddressesRoute: ProfileAddressesRoute,
  ProfileNotificationsRoute: ProfileNotificationsRoute,
  ProfileOrderHistoryRoute: ProfileOrderHistoryRoute,
  ProfilePaymentsRoute: ProfilePaymentsRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProfileHelpChatRoute: ProfileHelpChatRoute,
  ProfilePlaceholderSlugRoute: ProfilePlaceholderSlugRoute,
  ProfilePrivacy2faRoute: ProfilePrivacy2faRoute,
  ProfileHelpIndexRoute: ProfileHelpIndexRoute,
  ProfilePrivacyIndexRoute: ProfilePrivacyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
